### ISSUE TITLE
Migrations broken

### ISSUE THREAD

**Issue by brianmay** [melbournebioinformatics/karaage#17]
As per private email; this is with mysql in Debian wheezy:

```
root@debian-7:/home/vagrant# kg-manage migrate
Operations to perform:
  Synchronize unmigrated apps: pipeline, mptt, djcelery, captcha, django_tables2, ajax_select, jsonfield
  Apply all migrations: karaage, methods, sessions, sites, contenttypes, kgsoftware, kgusage, kgapplications
Synchronizing apps without migrations:
  Creating tables...
  Installing custom SQL...
  Installing indexes...
Running migrations:
  Applying karaage.0003_unique_groups... OK
  Applying karaage.0004_auto_karage4...Traceback (most recent call last):
  File "/usr/local/bin/kg-manage", line 7, in <module>
    execfile(__file__)
  File "/home/vagrant/src/karaage4/sbin/kg-manage", line 7, in <module>
    management.execute_from_command_line()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 160, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/usr/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 63, in migrate
    self.apply_migration(migration, fake=fake)
  File "/usr/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 97, in apply_migration
    migration.apply(project_state, schema_editor)
  File "/usr/lib/python2.7/dist-packages/django/db/migrations/migration.py", line 107, in apply
    operation.database_forwards(self.app_label, schema_editor, project_state, new_state)
  File "/usr/lib/python2.7/dist-packages/django/db/migrations/operations/special.py", line 69, in database_forwards
    schema_editor.execute(statement, params=None)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/schema.py", line 99, in execute
    cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 63, in execute
    return self.cursor.execute(sql)
  File "/usr/lib/python2.7/dist-packages/mysql/connector/django/base.py", line 133, in execute
    return self._execute_wrapper(self.cursor.execute, query, args)
  File "/usr/lib/python2.7/dist-packages/mysql/connector/django/base.py", line 125, in _execute_wrapper
    utils.DatabaseError(err.msg), sys.exc_info()[2])
  File "/usr/lib/python2.7/dist-packages/mysql/connector/django/base.py", line 113, in _execute_wrapper
    return method(query, args)
  File "/usr/lib/python2.7/dist-packages/mysql/connector/cursor.py", line 494, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/lib/python2.7/dist-packages/mysql/connector/connection.py", line 683, in cmd_query
    statement))
  File "/usr/lib/python2.7/dist-packages/mysql/connector/connection.py", line 601, in _handle_result
    raise errors.get_exception(packet)
django.db.utils.DatabaseError: Incorrect integer value: 'f' for column 'is_project_supervisor' at row 1
```

**Comment by brianmay** [comment]
Is there any database where '0' and '1' for True and False won't work?

**Comment by tysonclugg** [comment]
Sadly, yes.  I think the best course of action is to replace the SQL
migration code with Python code using the Django ORM - let Django sort out
the differences between database backends.

**Comment by tysonclugg** [comment]
Hmm... on second thoughts you're probably right.  Lines 606 and 613 of
karaage/migrations/0004_auto_karage4.py should probably be changed to 0.

**Comment by brianmay** [comment]
Fixed.
